### ISSUE TITLE
Dropdown label goes up

### ISSUE THREAD

**Issue by instrumaniak** [kima063/rest-countries#1]
In the main countries list page after selecting an item from the drop down menu, the label is misplaced on top. 

![01-dropdown](https://user-images.githubusercontent.com/8851360/115149560-84435880-a086-11eb-987d-d9875c609477.png)

Check your code against the [example](https://material-ui.com/components/selects/)

**Comment by maksuda-islam** [comment]
It's the default behavior of material UI's Select component.

**Comment by instrumaniak** [comment]
> It's the default behavior of material UI's Select component.

Yes, but the line crosses over the label. After applying a fix it would look like below:
![01-dropdown](https://user-images.githubusercontent.com/8851360/115152526-4a2c8380-a093-11eb-93c2-1ca69558f814.png)
